"""Add face encoding

Revision ID: e7fc847f9e39
Revises: a19e19db75ed
Create Date: 2026-03-03 18:31:22.701887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fc847f9e39'
down_revision: Union[str, None] = 'a19e19db75ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('face_encoding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'face_encoding')
    # ### end Alembic commands ###
